export type PlatformId = 'meta' | 'tiktok' | 'google' | 'youtube' | 'linkedin' | 'pinterest';
export type CampaignGoal = 'awareness' | 'traffic' | 'conversions' | 'leads' | 'app_installs' | 'sales';

export interface PlatformInfo {
  id: PlatformId;
  name: string;
  icon: string;
  color: string;
  bgGradient: string;
  description: string;
  bestFor: string[];
  avgCPC: string;
  avgCPM: string;
  minBudget: string;
  audienceSize: string;
  keyFeatures: string[];
  pros: string[];
  cons: string[];
  tips: string[];
  commonMistakes: string[];
  checklist: string[];
  targetDemographics: string[];
  adFormats: string[];
}

export interface CampaignGoalInfo {
  id: CampaignGoal;
  name: string;
  icon: string;
  description: string;
  recommendedPlatforms: PlatformId[];
  keyMetrics: string[];
  tips: string[];
}

export const platforms: Record<PlatformId, PlatformInfo> = {
  meta: {
    id: 'meta',
    name: 'Meta Ads',
    icon: 'Facebook',
    color: '#1877F2',
    bgGradient: 'from-blue-600 to-blue-400',
    description: 'Reach billions across Facebook and Instagram with the most powerful social advertising platform. Meta Ads offer unparalleled targeting precision with rich audience data, making them ideal for businesses of all sizes looking to drive conversions, build brand awareness, or generate leads.',
    bestFor: ['E-commerce & Retail', 'Brand Awareness', 'Lead Generation', 'App Installs', 'Retargeting', 'Local Business'],
    avgCPC: '$0.50 - $2.00',
    avgCPM: '$5.00 - $15.00',
    minBudget: '$5/day',
    audienceSize: '3+ billion users',
    keyFeatures: [
      'Advanced audience targeting (interests, behaviors, lookalikes)',
      'Dynamic Creative Optimization (DCO)',
      'Cross-platform placement (FB, IG, Messenger, Audience Network)',
      'Pixel tracking & conversion optimization',
      'A/B testing framework',
      'Custom & lookalike audiences',
    ],
    pros: [
      'Largest social media audience globally',
      'Extremely granular targeting options',
      'Powerful retargeting capabilities',
      'Robust analytics and reporting tools',
      'Large variety of ad formats',
      '成熟的机器学习算法自动优化',
    ],
    cons: [
      'Rising costs in competitive industries',
      'iOS privacy changes reduced tracking accuracy',
      'Ad fatigue can set in quickly with small audiences',
      'Learning account requires consistent spend',
      'Complex interface for beginners',
    ],
    tips: [
      'Start with Advantage+ campaigns for automated optimization',
      'Use broad audiences and let the algorithm learn',
      'Refresh creatives every 2-3 weeks to avoid ad fatigue',
      'Install the Meta Pixel before launching any campaign',
      'Use lookalike audiences based on your best customers',
      'Test at least 3-5 ad creatives per campaign',
      'Start with conversion objective, not traffic',
      'Use UTM parameters to track ad performance in Google Analytics',
    ],
    commonMistakes: [
      'Targeting too narrow audience (under 1,000 people)',
      'Not using the Meta Pixel or Conversions API',
      'Changing campaigns too frequently (let them learn for 7 days)',
      'Using traffic objective when you want conversions',
      'Ignoring audience overlap between ad sets',
      'Not setting up proper conversion tracking',
      'Overspending on a single ad set without testing',
      'Neglecting to create multiple creative variations',
    ],
    checklist: [
      'Install Meta Pixel on your website',
      'Set up Conversions API (CAPI) for server-side tracking',
      'Define your primary conversion event',
      'Create 3-5 ad creative variations',
      'Set up your business manager account',
      'Verify your domain in Business Manager',
      'Create custom audiences from your customer data',
      'Build lookalike audiences (1%, 3%, 5%)',
      'Set a realistic daily budget',
      'Choose the right campaign objective',
      'Configure ad scheduling for peak hours',
      'Set up UTM tracking parameters',
    ],
    targetDemographics: ['Ages 25-54', 'Mixed gender split', 'Global reach', 'All income levels', 'Urban and suburban'],
    adFormats: ['Image Ads', 'Video Ads', 'Carousel Ads', 'Stories Ads', 'Reels Ads', 'Collection Ads', 'Lead Forms'],
  },
  tiktok: {
    id: 'tiktok',
    name: 'TikTok Ads',
    icon: 'TikTok',
    color: '#000000',
    bgGradient: 'from-gray-900 to-pink-500',
    description: 'Tap into the fastest-growing social platform with highly engaging short-form video ads. TikTok Ads are perfect for brands targeting younger demographics and those looking to create viral, shareable content that drives massive awareness and engagement.',
    bestFor: ['Brand Awareness', 'E-commerce', 'Viral Marketing', 'Gen Z Audience', 'App Installs', 'Entertainment'],
    avgCPC: '$0.20 - $1.50',
    avgCPM: '$2.00 - $10.00',
    minBudget: '$20/day',
    audienceSize: '1.5+ billion users',
    keyFeatures: [
      'Spark Ads (boost organic content)',
      'In-feed video ads',
      'TopView & Brand Takeover ads',
      'Branded Hashtag Challenges',
      'Branded Effects & AR filters',
      'Smart Performance Campaigns',
    ],
    pros: [
      'Lower CPM compared to Meta & Google',
      'Highly engaged younger audience',
      'Strong organic amplification potential',
      'Native-feeling ad format (Ugc-style)',
      'Growing rapidly in all demographics',
      'Less saturated ad marketplace',
    ],
    cons: [
      'Limited to short-form vertical video',
      'Harder to track conversions accurately',
      'Best for B2C, not ideal for B2B',
      'Content needs to feel authentic and native',
      'Less precise targeting than Meta',
      'Smaller advertiser tool ecosystem',
    ],
    tips: [
      'Use UGC-style content that feels native to the platform',
      'Hook viewers in the first 1-2 seconds',
      'Add captions to all videos (many users watch without sound)',
      'Use trending sounds and music to boost relevance',
      'Leverage TikTok influencers for creative inspiration',
      'Start with Spark Ads to boost your best organic posts',
      'Use the " swipe up" CTA for web traffic campaigns',
      'Test 5-10 creatives to find winning content',
    ],
    commonMistakes: [
      'Using polished, corporate-style video content',
      'Ignoring the importance of the first 1-2 seconds',
      'Not adding captions or text overlays',
      'Targeting too broad without testing',
      'Not leveraging trending sounds and effects',
      'Running ads without building organic presence first',
      'Setting conversion objectives without proper tracking',
      'Ignoring TikTok Shop features for e-commerce',
    ],
    checklist: [
      'Create a TikTok Business account',
      'Install TikTok Pixel on your website',
      'Set up TikTok Events API',
      'Research trending content in your niche',
      'Create 5-10 UGC-style video creatives',
      'Add captions/text overlays to all videos',
      'Set up conversion tracking',
      'Define your target age range and interests',
      'Choose campaign objective based on goal',
      'Set a minimum budget of $20/day',
      'Plan creative refresh schedule (weekly)',
      'Set up A/B testing for ad variants',
    ],
    targetDemographics: ['Ages 16-34 (core)', 'Growing 35+ demographic', 'Slight female skew', 'Global reach', 'Mobile-first users'],
    adFormats: ['In-Feed Ads', 'TopView Ads', 'Brand Takeover', 'Spark Ads', 'Branded Hashtag Challenge', 'Branded Effects'],
  },
  google: {
    id: 'google',
    name: 'Google Ads',
    icon: 'Search',
    color: '#4285F4',
    bgGradient: 'from-green-500 to-yellow-400',
    description: 'Capture intent-driven traffic across Google Search, Display Network, YouTube, and more. Google Ads is the gold standard for reaching people actively searching for your products or services, offering the highest intent-to-purchase traffic available.',
    bestFor: ['Lead Generation', 'E-commerce', 'Local Business', 'B2B Services', 'High-Intent Purchases', 'App Installs'],
    avgCPC: '$1.00 - $5.00',
    avgCPM: '$2.00 - $20.00',
    minBudget: '$10/day',
    audienceSize: '8.5+ billion searches/day',
    keyFeatures: [
      'Search, Display, YouTube, Shopping, App campaigns',
      'Smart Bidding (Performance Max)',
      'Keyword targeting and negative keywords',
      'Ad extensions (sitelinks, callouts, structured snippets)',
      'Remarketing audiences',
      'Google Merchant Center integration',
    ],
    pros: [
      'Captures high-intent search traffic',
      'Massive reach across multiple Google properties',
      'Detailed performance tracking and attribution',
      'Mature platform with extensive documentation',
      'Smart Bidding automates optimization',
      'Excellent for local businesses with Google Maps',
    ],
    cons: [
      'Can be expensive in competitive industries',
      'Requires keyword research expertise',
      'Click fraud can be an issue',
      'Display network can waste budget if not optimized',
      'Learning curve for campaign setup',
      'Quality Score heavily impacts costs',
    ],
    tips: [
      'Use Exact and Phrase match keywords to control spend',
      'Add negative keywords regularly to filter junk traffic',
      'Write ad copy that matches search intent exactly',
      'Use all relevant ad extensions for better CTR',
      'Start with Search campaigns, then expand to Display',
      'Set up conversion tracking for all key actions',
      'Use Performance Max for full-funnel campaigns',
      'Monitor Quality Score and optimize low-scoring keywords',
    ],
    commonMistakes: [
      'Using only Broad match keywords',
      'Not adding negative keywords',
      'Ignoring Quality Score',
      'Not setting up conversion tracking',
      'Using too many keywords per ad group',
      'Not utilizing ad extensions',
      'Sending all traffic to homepage instead of landing pages',
      'Not reviewing search terms report regularly',
    ],
    checklist: [
      'Set up Google Analytics 4 with enhanced measurement',
      'Link Google Ads with Google Analytics',
      'Set up conversion actions (purchase, lead, signup)',
      'Create dedicated landing pages for each ad group',
      'Conduct keyword research (use Google Keyword Planner)',
      'Organize keywords into tight ad groups',
      'Write compelling ad copy with clear CTAs',
      'Set up all relevant ad extensions',
      'Configure negative keyword list',
      'Set daily budget and bidding strategy',
      'Enable auto-bidding if unsure about manual CPC',
      'Set up remarketing lists for future campaigns',
    ],
    targetDemographics: ['All ages', 'All income levels', 'Business professionals', 'Local customers', 'Global reach'],
    adFormats: ['Search Ads', 'Display Ads', 'Shopping Ads', 'Video Ads (YouTube)', 'App Ads', 'Performance Max', 'Local Ads'],
  },
  youtube: {
    id: 'youtube',
    name: 'YouTube Ads',
    icon: 'Youtube',
    color: '#FF0000',
    bgGradient: 'from-red-600 to-red-400',
    description: 'Leverage the world\'s second-largest search engine with video advertising that drives brand awareness and consideration. YouTube Ads reach over 2 billion monthly active users, making it an essential platform for video-first marketing strategies.',
    bestFor: ['Brand Awareness', 'Product Demo', 'Thought Leadership', 'Retargeting', 'Long-Form Storytelling', 'Tutorial Marketing'],
    avgCPC: '$0.30 - $3.00',
    avgCPM: '$6.00 - $30.00',
    minBudget: '$10/day',
    audienceSize: '2.5+ billion monthly users',
    keyFeatures: [
      'Skippable & non-skippable in-stream ads',
      'Bumper ads (6 seconds)',
      'Discovery ads (search results)',
      'Overlay & display ads',
      'Masthead & homepage takeover',
      'YouTube Shorts ads',
    ],
    pros: [
      'Massive global reach across all demographics',
      'High engagement with video content',
      'Strong brand recall compared to other formats',
      'Can target by topic, keyword, or placement',
      'YouTube Shorts reaching huge engagement',
      'Integration with Google Ads ecosystem',
    ],
    cons: [
      'Higher CPM than social platforms',
      'Video production can be expensive',
      'Skip rates can be very high (skippable ads)',
      'Requires high-quality video content',
      'Longer creative production timelines',
      'Limited direct conversion tracking vs Search',
    ],
    tips: [
      'Hook viewers in the first 5 seconds before the skip button appears',
      'Use bumper ads for frequency and brand recall',
      'Retarget website visitors with YouTube display ads',
      'Leverage YouTube influencers for authentic content',
      'Create different video lengths for different placements',
      'Add end screens and cards to drive further engagement',
      'Use custom intent audiences for high-intent targeting',
      'Optimize your YouTube channel for organic growth alongside ads',
    ],
    commonMistakes: [
      'Starting with a slow intro (viewers skip after 5 seconds)',
      'Not having a clear call-to-action',
      'Using low-quality video production',
      'Targeting too broad without specific interests',
      'Not using frequency capping',
      'Ignoring YouTube Shorts as an ad format',
      'Not retargeting engaged viewers',
      'Creating one-size-fits-all video ads',
    ],
    checklist: [
      'Set up Google Ads account with video campaign access',
      'Link YouTube channel to Google Ads',
      'Create multiple video ad lengths (15s, 30s, 60s)',
      'Create bumper ad version (6 seconds)',
      'Set up conversion tracking for video campaigns',
      'Define target audience demographics and interests',
      'Choose bidding strategy (CPV, Target CPM, Maximize conversions)',
      'Set up remarketing audiences from website data',
      'Create compelling first 5 seconds (hook)',
      'Add clear CTA in video and overlay',
      'Set frequency caps to avoid overexposure',
      'Plan A/B testing for different creative angles',
    ],
    targetDemographics: ['Ages 18-55', 'Nearly equal gender split', 'All income levels', 'Global audience', 'Education-oriented users'],
    adFormats: ['Skippable In-Stream', 'Non-Skippable In-Stream', 'Bumper Ads', 'Discovery Ads', 'Overlay Ads', 'Shorts Ads'],
  },
  linkedin: {
    id: 'linkedin',
    name: 'LinkedIn Ads',
    icon: 'Linkedin',
    color: '#0A66C2',
    bgGradient: 'from-blue-700 to-blue-500',
    description: 'Reach professionals and decision-makers with B2B-focused advertising on the world\'s largest professional network. LinkedIn Ads offer unmatched targeting by job title, company, industry, and seniority level.',
    bestFor: ['B2B Lead Generation', 'Recruiting', 'Thought Leadership', 'Enterprise Sales', 'Content Marketing', 'Webinar Promotion'],
    avgCPC: '$5.00 - $15.00',
    avgCPM: '$30.00 - $80.00',
    minBudget: '$10/day',
    audienceSize: '900+ million users',
    keyFeatures: [
      'Professional targeting (job title, company size, industry)',
      'Lead Gen Forms with auto-fill',
      'Matched Audiences (website retargeting, contact list)',
      'Sponsored Content, InMail, and Text Ads',
      'Audience expansion and lookalikes',
      'Conversation Ads for engagement',
    ],
    pros: [
      'Best B2B targeting capabilities available',
      'Access to decision-makers and professionals',
      'Lead Gen Forms with high auto-fill rates',
      'Professional context increases trust',
      'Detailed firmographic targeting',
      'Lower competition than consumer platforms',
    ],
    cons: [
      'Most expensive CPC and CPM among all platforms',
      'Limited audience size compared to Meta/Google',
      'Organic reach requires consistent content strategy',
      'Ad formats are more limited',
      'Not suitable for B2C targeting',
      'Longer sales cycles require patience',
    ],
    tips: [
      'Use Lead Gen Forms for maximum conversion rates',
      'Target by job title, not just industry',
      'Keep ad copy professional and value-driven',
      'Use single image ads (they often outperform)',
      'A/B test your headline - it makes or breaks performance',
      'Nurture leads with retargeting campaigns',
      'Use Account-Based Marketing for enterprise targets',
      'Align ad content with your content marketing strategy',
    ],
    commonMistakes: [
      'Targeting too broad of an audience',
      'Using casual or informal ad copy',
      'Not using Lead Gen Forms',
      'Targeting by industry only (missing job titles)',
      'Setting budgets too low for meaningful results',
      'Not following up on leads promptly',
      'Ignoring the importance of company page quality',
      'Not testing different ad formats',
    ],
    checklist: [
      'Set up LinkedIn Campaign Manager',
      'Complete your Company Page with all details',
      'Install LinkedIn Insight Tag on your website',
      'Set up Matched Audiences (email list, website visitors)',
      'Define target job titles and seniority levels',
      'Create professional ad creatives (1200x627 images)',
      'Set up Lead Gen Forms with relevant fields',
      'Write B2B-focused ad copy with clear value proposition',
      'Set appropriate budget (start at $30-50/day for B2B)',
      'Configure conversion tracking',
      'Plan lead nurture follow-up sequence',
      'Set up A/B tests for headlines and creatives',
    ],
    targetDemographics: ['Ages 25-55 professionals', 'College-educated', 'Mid to high income', 'Business decision-makers', 'Global professional network'],
    adFormats: ['Sponsored Content', 'Message Ads (InMail)', 'Text Ads', 'Dynamic Ads', 'Conversation Ads', 'Lead Gen Forms'],
  },
  pinterest: {
    id: 'pinterest',
    name: 'Pinterest Ads',
    icon: 'Pin',
    color: '#E60023',
    bgGradient: 'from-red-500 to-orange-400',
    description: 'Reach users in a discovery and planning mindset with visual advertising. Pinterest is uniquely powerful for e-commerce, home decor, fashion, food, and DIY niches, with users actively searching for products and ideas to purchase.',
    bestFor: ['E-commerce', 'Home Decor', 'Fashion & Beauty', 'Food & Recipes', 'DIY & Crafts', 'Wedding Planning'],
    avgCPC: '$0.10 - $1.50',
    avgCPM: '$2.00 - $10.00',
    minBudget: '$5/day',
    audienceSize: '500+ million users',
    keyFeatures: [
      'Shopping Pins with direct purchase links',
      'Idea Pins for brand awareness',
      'Search-based targeting (intent-driven)',
      'Audience targeting & retargeting',
      'Pinterest Trends data',
      'Catalog integration for e-commerce',
    ],
    pros: [
      'Users are in a planning/purchase mindset',
      'Lower costs compared to Meta and Google',
      'Long pin lifespan (pins can drive traffic for months)',
      'Strong for niche and lifestyle categories',
      'Shopping features drive direct sales',
      'Less ad competition than major platforms',
    ],
    cons: [
      'Limited audience size compared to big platforms',
      'Best for visual/product-based businesses only',
      'Organic reach requires consistent pinning',
      'Analytics less sophisticated than Meta/Google',
      'Smaller advertiser tool ecosystem',
      'Limited B2B applicability',
    ],
    tips: [
      'Create multiple Pin formats (standard, video, carousel)',
      'Use text overlays on images to increase click-through',
      'Optimize Pin descriptions with keywords (Pinterest is a search engine)',
      'Pin consistently to build organic presence alongside ads',
      'Use Pinterest Trends to discover seasonal opportunities',
      'Link Pins directly to product pages for shopping campaigns',
      'Create lifestyle imagery rather than product-only shots',
      'Use tall images (2:3 ratio) for maximum visibility',
    ],
    commonMistakes: [
      'Using low-quality or small images',
      'Not optimizing Pin descriptions with keywords',
      'Only pinning product images without lifestyle context',
      'Ignoring seasonal trends and planning ahead',
      'Not using Pinterest catalog for e-commerce',
      'Setting conversion objectives without tracking setup',
      'Not creating enough Pin variations for testing',
      'Expecting immediate results (Pinterest is a long-term play)',
    ],
    checklist: [
      'Create a Pinterest Business account',
      'Claim your website in Pinterest settings',
      'Install Pinterest Tag on your website',
      'Set up Pinterest Catalog for product Pins',
      'Create rich Pins for your website content',
      'Research keywords using Pinterest Trends',
      'Create 10-15 Pin images in 2:3 ratio',
      'Write keyword-rich Pin descriptions',
      'Set up conversion tracking events',
      'Choose campaign objective (awareness, consideration, conversion)',
      'Set daily budget and bidding strategy',
      'Plan content calendar for consistent Pin creation',
    ],
    targetDemographics: ['Ages 25-45 (core)', '80% female user base', 'Higher income households', 'Purchase-minded users', 'US, UK, France, Germany, Canada'],
    adFormats: ['Standard Pins', 'Video Pins', 'Carousel Pins', 'Shopping Pins', 'Collection Ads', 'Idea Pins'],
  },
};

export const campaignGoals: Record<CampaignGoal, CampaignGoalInfo> = {
  awareness: {
    id: 'awareness',
    name: 'Brand Awareness',
    icon: 'Eye',
    description: 'Get your brand in front of as many relevant people as possible. Ideal for new product launches, brand repositioning, or entering new markets.',
    recommendedPlatforms: ['meta', 'tiktok', 'youtube', 'pinterest'],
    keyMetrics: ['Impressions', 'Reach', 'Brand Lift', 'Ad Recall', 'Video Views', 'CPM'],
    tips: [
      'Focus on reach and frequency, not clicks',
      'Use visually striking creatives that stop the scroll',
      'Leverage video content for higher engagement',
      'Set frequency caps to avoid annoying your audience',
      'Test different audiences to find your ideal customer profile',
    ],
  },
  traffic: {
    id: 'traffic',
    name: 'Website Traffic',
    icon: 'MousePointerClick',
    description: 'Drive qualified visitors to your website or landing pages. Best when you have optimized landing pages ready to convert incoming traffic.',
    recommendedPlatforms: ['google', 'meta', 'pinterest'],
    keyMetrics: ['Clicks', 'CTR', 'CPC', 'Bounce Rate', 'Pages/Session', 'Session Duration'],
    tips: [
      'Create dedicated landing pages matching your ad copy',
      'Use UTM parameters to track traffic sources',
      'Ensure landing pages load fast on mobile',
      'A/B test different headlines and images',
      'Retarget visitors who did not convert',
    ],
  },
  conversions: {
    id: 'conversions',
    name: 'Conversions',
    icon: 'Target',
    description: 'Drive specific actions like purchases, signups, or downloads. Requires proper conversion tracking setup for optimal results.',
    recommendedPlatforms: ['google', 'meta', 'tiktok'],
    keyMetrics: ['Conversions', 'CPA', 'ROAS', 'Conversion Rate', 'Cost per Acquisition', 'Revenue'],
    tips: [
      'Install tracking pixels/tags before launching',
      'Optimize landing pages for conversions first',
      'Start with conversion-optimized campaigns',
      'Use retargeting to convert warm audiences',
      'Monitor ROAS closely and adjust bids accordingly',
    ],
  },
  leads: {
    id: 'leads',
    name: 'Lead Generation',
    icon: 'UserPlus',
    description: 'Collect contact information from potential customers. Perfect for B2B companies, service providers, and businesses with longer sales cycles.',
    recommendedPlatforms: ['linkedin', 'meta', 'google'],
    keyMetrics: ['Leads', 'CPL', 'Lead Quality Score', 'Form Completion Rate', 'Cost per Qualified Lead', 'Pipeline Value'],
    tips: [
      'Use native lead forms to reduce friction',
      'Ask for minimum required fields only',
      'Offer valuable lead magnets (ebooks, webinars, demos)',
      'Qualify leads with follow-up questions',
      'Set up lead scoring to prioritize high-value prospects',
    ],
  },
  app_installs: {
    id: 'app_installs',
    name: 'App Installs',
    icon: 'Smartphone',
    description: 'Drive mobile app downloads and engagement. Ideal for mobile-first businesses, gaming apps, and utility applications.',
    recommendedPlatforms: ['meta', 'tiktok', 'google'],
    keyMetrics: ['Installs', 'CPI', 'Retention Rate', 'Cost per Install', 'LTV', 'ROAS'],
    tips: [
      'Use app install campaigns with deep linking',
      'Optimize your app store listing (screenshots, description)',
      'Target lookalike audiences of existing app users',
      'Retarget non-converters with special offers',
      'Track post-install events (signups, purchases) for optimization',
    ],
  },
  sales: {
    id: 'sales',
    name: 'Sales & Revenue',
    icon: 'DollarSign',
    description: 'Directly drive online and offline sales. Requires e-commerce tracking and product catalogs for optimal performance.',
    recommendedPlatforms: ['google', 'meta', 'pinterest'],
    keyMetrics: ['Revenue', 'ROAS', 'AOV', 'Purchase Conversion Rate', 'Cost per Purchase', 'Return Rate'],
    tips: [
      'Set up product catalogs with all items',
      'Use dynamic product ads for retargeting',
      'Offer exclusive ad-only promotions',
      'Implement abandoned cart recovery campaigns',
      'Optimize for ROAS, not just clicks or conversions',
    ],
  },
};

export const industryBenchmarks: Record<string, { avgCPA: string; avgROAS: string; avgCTR: string }> = {
  'E-commerce': { avgCPA: '$10 - $30', avgROAS: '4x - 8x', avgCTR: '1.5% - 3%' },
  'SaaS / B2B': { avgCPA: '$50 - $200', avgROAS: '3x - 5x', avgCTR: '0.5% - 1.5%' },
  'Real Estate': { avgCPA: '$20 - $80', avgROAS: '5x - 12x', avgCTR: '1% - 2%' },
  'Education': { avgCPA: '$15 - $60', avgROAS: '3x - 6x', avgCTR: '0.8% - 2%' },
  'Healthcare': { avgCPA: '$30 - $100', avgROAS: '4x - 8x', avgCTR: '0.6% - 1.5%' },
  'Finance': { avgCPA: '$40 - $150', avgROAS: '5x - 10x', avgCTR: '0.5% - 1.2%' },
  'Restaurants': { avgCPA: '$5 - $15', avgROAS: '3x - 6x', avgCTR: '2% - 5%' },
  'Fashion & Beauty': { avgCPA: '$8 - $25', avgROAS: '4x - 9x', avgCTR: '1.5% - 4%' },
  'Technology': { avgCPA: '$30 - $120', avgROAS: '3x - 7x', avgCTR: '0.7% - 1.8%' },
  'Travel': { avgCPA: '$10 - $40', avgROAS: '5x - 10x', avgCTR: '1% - 3%' },
};
